version: "2"
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - "MINIO_ROOT_USER=root"
      - "MINIO_ROOT_PASSWORD=testpassword"
    command: server /data --console-address ":9090"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 root testpassword;
      /usr/bin/mc mb myminio/users;
      /usr/bin/mc anonymous set public myminio/users;
      exit 0;
      "