version: '3'
services:

  redis:
    container_name: redis-container
    image: redis:latest
    command: redis-server --appendonly yes --requirepass testpassword
    ports:
      - "6379:6379"
    environment:
      TZ: JST-9

  redisCommander:
    container_name: redis-commander-container
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: Users:redis-container:6379:0:testpassword,TestTable:redis-container:6379:1:testpassword
      TZ: JST-9
    ports:
      - "8081:8081"
    depends_on:
      - redis